### ISSUE TITLE
Version on NPM is not in commonjs

### ISSUE THREAD

**Issue by jaxoncreed** [rdfjs-base/dataset#11]
In version `2.0.0`, this library uses ES Modules and not everything is compatible with ESM. The main problem I've run into is that fact that Jest only has experimental support for ESM (https://jestjs.io/docs/ecmascript-modules). This means it's difficult to test any project that includes this library. The same goes for @rdfjs/data-model. 

This would be fine if the code used CommonJS. Would it be possible to rewrite this library using commonjs, or use a transpiler that translates to CommonJS?

**Comment by bergos** [comment]
Please switch to the older major version if you need CommonJS. The new version is intentional ESM only and build system free to keep the time required for maintenance low. If you are concerned about using an outdated version, don't worry, the old version will not get any new features, but reported bugs will still be fixed. That's the case for all rdfjs-base and rdf-ext packages.
